[project]
name = "supabase_functions_error_handling"
version = "0.1.0"
description = "Test error handling in Supabase functions"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "python-dotenv>=1.0.1",
    "supabase>=2.15.1",
]

[dependency-groups]
dev = [
    "ruff>=0.9.2",
]
