[project]
name = "supabase-signout-scope"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastapi[all]>=0.115.6",
    "python-dotenv>=1.0.1",
    "supabase>=2.13.0",
]
